#!/bin/bash

# =============================================================================
# Script: copy-env.sh
# Mục đích: Copy .env.example sang .env, tự động tạo secrets và set COMPOSE_FILE
#
# Cách dùng:
#   ./scripts/copy-env.sh                          # Dev (mặc định)
#   ./scripts/copy-env.sh --env prod               # Production
#   ./scripts/copy-env.sh --env prod --force        # Production, ghi đè .env cũ
#   ./scripts/copy-env.sh --env prod . ./strapi     # Production, nhiều thư mục
# =============================================================================

set -euo pipefail

# ── Parse Arguments ──────────────────────────────────────────────────────────
FORCE=0
ENV_MODE="dev"
PATHS=()

for arg in "$@"; do
  case "$arg" in
    --force|-f) FORCE=1 ;;
    --env)      ;; # handled below via shift logic
    dev|prod)
      # Accept bare dev/prod only if preceded by --env
      if [ "${PREV_ARG:-}" = "--env" ]; then
        ENV_MODE="$arg"
      else
        PATHS+=("$arg")
      fi
      ;;
    *)          PATHS+=("$arg") ;;
  esac
  PREV_ARG="$arg"
done

if [ ${#PATHS[@]} -eq 0 ]; then
  PATHS=(".")
fi

# ── Compose File Mapping ────────────────────────────────────────────────────
case "$ENV_MODE" in
  dev)  COMPOSE_FILE_VALUE="compose.yml" ;;
  prod) COMPOSE_FILE_VALUE="compose.prod.yml" ;;
  *)
    echo "❌ [Error] Unknown environment: $ENV_MODE. Use 'dev' or 'prod'."
    exit 1
    ;;
esac

echo ""
echo "🔧 Environment: $ENV_MODE → COMPOSE_FILE=$COMPOSE_FILE_VALUE"

# ── Process Each Directory ───────────────────────────────────────────────────
for TARGET_DIR in "${PATHS[@]}"; do
  echo ""

  # Tên thư mục để hiển thị
  if [ "$TARGET_DIR" = "." ]; then
    DIR_NAME="Root"
  else
    DIR_NAME=$(basename "$TARGET_DIR")
  fi

  echo "--- 📂 Processing Environment: $DIR_NAME ---"

  EXAMPLE_PATH="$TARGET_DIR/.env.example"
  ENV_PATH="$TARGET_DIR/.env"

  if [ ! -f "$EXAMPLE_PATH" ]; then
    echo "  ❌ [Error] .env.example not found at: $EXAMPLE_PATH"
    continue
  fi

  SKIP_COPY=0
  if [ -f "$ENV_PATH" ] && [ $FORCE -eq 0 ]; then
    echo "  ⏩ [Skip] .env already exists. Secrets and variables are kept intact."
    SKIP_COPY=1
  fi

  if [ $SKIP_COPY -eq 0 ]; then
    # 1. Copy example → .env
    cp "$EXAMPLE_PATH" "$ENV_PATH"

    # 2. Replace placeholder secrets
    if command -v perl &> /dev/null; then
      perl -pi -e 's/tobemodified[a-zA-Z0-9_]*/qx(openssl rand -base64 32 | tr -d "\n")/gie' "$ENV_PATH"
    else
      echo "  ⚠️ [Warning] Perl not found. Using sed fallback (same secret for all)."
      SECRET=$(openssl rand -base64 32 | tr -d '\n' | sed 's/[\/&]/\\&/g')
      sed -i.bak "s/tobemodified[a-zA-Z0-9_]*/$SECRET/gi" "$ENV_PATH"
      rm -f "$ENV_PATH.bak"
    fi
  fi

  # 3. Inject COMPOSE_FILE (chỉ cho Root .env)
  if [ "$DIR_NAME" = "Root" ]; then
    # Xóa dòng COMPOSE_FILE cũ (nếu có) và thêm mới
    sed -i.bak '/^COMPOSE_FILE=/d' "$ENV_PATH"
    rm -f "$ENV_PATH.bak"

    # Thêm COMPOSE_FILE vào đầu file với comment
    {
      echo "# Docker Compose (auto-generated by copy-env.sh --env $ENV_MODE)"
      echo "COMPOSE_FILE=$COMPOSE_FILE_VALUE"
      echo ""
      cat "$ENV_PATH"
    } > "$ENV_PATH.tmp" && mv "$ENV_PATH.tmp" "$ENV_PATH"
  fi

  if [ $SKIP_COPY -eq 0 ]; then
    echo "  ✅ [Success] Created .env with fresh random secrets at $ENV_PATH"
  else
    echo "  ✅ [Success] Updated COMPOSE_FILE=$COMPOSE_FILE_VALUE in $ENV_PATH"
  fi
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 Done! Bạn giờ chỉ cần gõ: docker compose ps"
echo "   (không cần -f $COMPOSE_FILE_VALUE nữa)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
