<#
.SYNOPSIS
  Copy .env.example sang .env, auto-generate secrets va set COMPOSE_FILE

.DESCRIPTION
  Tuong duong voi copy-env.sh nhung chay tren Windows (PowerShell)

.EXAMPLE
  .\scripts\copy-env.ps1                          # Dev (mac dinh)
  .\scripts\copy-env.ps1 -Env prod                # Production
  .\scripts\copy-env.ps1 -Env prod -Force          # Production, ghi de .env cu
  .\scripts\copy-env.ps1 -Env prod -Paths ".", "./strapi"
#>

param(
  [ValidateSet("dev", "prod")]
  [string]$Env = "dev",

  [switch]$Force,

  [string[]]$Paths = @(".")
)

# ── Strict Mode ──────────────────────────────────────────────────────────────
$ErrorActionPreference = "Stop"

# ── Helper: Generate Random Secret ──────────────────────────────────────────
function New-Secret {
  param([int]$Bytes = 32)
  $randomBytes = New-Object byte[] $Bytes
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($randomBytes)
  return [Convert]::ToBase64String($randomBytes)
}

# ── Compose File Mapping ────────────────────────────────────────────────────
$composeFileMap = @{
  "dev"  = "compose.yml"
  "prod" = "compose.prod.yml"
}
$composeFileValue = $composeFileMap[$Env]

Write-Host ""
Write-Host "🔧 Environment: $Env → COMPOSE_FILE=$composeFileValue" -ForegroundColor Cyan

# ── Process Each Directory ───────────────────────────────────────────────────
foreach ($targetDir in $Paths) {
  Write-Host ""

  $absoluteDir = Resolve-Path -Path $targetDir -ErrorAction SilentlyContinue
  if (-not $absoluteDir) {
    Write-Host "  ❌ [Error] Directory not found: $targetDir" -ForegroundColor Red
    continue
  }

  $dirName = if ($targetDir -eq ".") { "Root" } else { Split-Path $absoluteDir -Leaf }
  Write-Host "--- 📂 Processing Environment: $dirName ---"

  $examplePath = Join-Path $absoluteDir ".env.example"
  $envPath     = Join-Path $absoluteDir ".env"

  # 1. Check .env.example exists
  if (-not (Test-Path $examplePath)) {
    Write-Host "  ❌ [Error] .env.example not found at: $examplePath" -ForegroundColor Red
    continue
  }

  # 2. Check .env already exists
  if ((Test-Path $envPath) -and -not $Force) {
    Write-Host "  ⏩ [Skip] .env already exists. Use -Force to overwrite." -ForegroundColor Yellow
    continue
  }

  # 3. Read example, replace placeholders with unique secrets
  $content = Get-Content $examplePath -Raw
  $replacementCount = 0

  $content = [regex]::Replace($content, 'tobemodified[a-zA-Z0-9_]*', {
    $script:replacementCount++
    return (New-Secret)
  }, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)

  # 4. Inject COMPOSE_FILE (only for Root .env)
  if ($dirName -eq "Root") {
    # Remove existing COMPOSE_FILE line if present
    $content = ($content -split "`n" | Where-Object { $_ -notmatch '^COMPOSE_FILE=' }) -join "`n"

    # Prepend COMPOSE_FILE
    $header = "# Docker Compose (auto-generated by copy-env.ps1 -Env $Env)`nCOMPOSE_FILE=$composeFileValue`n`n"
    $content = $header + $content
  }

  # 5. Write .env
  $content | Set-Content -Path $envPath -NoNewline -Encoding UTF8
  Write-Host "  ✅ [Success] Created .env with $replacementCount fresh random secrets." -ForegroundColor Green
}

Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
Write-Host "🎉 Done! Ban gio chi can go: docker compose ps" -ForegroundColor Green
Write-Host "   (khong can -f $composeFileValue nua)" -ForegroundColor Green
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
